name: Deploy to Proxmox

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t ticket-poc .

      - name: Stop existing container (if any)
        run: |
          docker stop ticket-poc || true
          docker rm ticket-poc || true

      - name: Run Postgres
        run: |
          docker run -d --name ticket-pg --restart unless-stopped -e POSTGRES_USER=app -e POSTGRES_PASSWORD=app -e POSTGRES_DB=app -p 5432:5432 postgres:16-alpine

      - name: Wait for Postgres
        run: |
          for i in {1..30}; do
            (echo > /dev/tcp/127.0.0.1/5432) >/dev/null 2>&1 && break || sleep 1;
          done

      - name: Run app container
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          docker run -d \
            --name ticket-poc \
            --restart unless-stopped \
            -p 3000:3000 \
            -e DATABASE_URL="${DATABASE_URL:-postgres://app:app@127.0.0.1:5432/app}" \
            -e JWT_SECRET="$JWT_SECRET" \
            ticket-poc