name: Deploy to Proxmox

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies (for Drizzle CLI)
        run: |
          npm ci

      - name: Generate migrations (Drizzle)
        run: |
          npm run db:generate

      - name: Run migrations (Drizzle)
        run: |
          npm run db:migrate

      - name: Build Docker image
        run: |
          docker build \
            --build-arg SKIP_ENV_VALIDATION=true \
            -t ticket-poc .

      - name: Stop existing container (if any)
        run: |
          docker stop ticket-poc || true
          docker rm ticket-poc || true

      - name: Run app container
        run: |
          docker run -d \
            --name ticket-poc \
            --restart unless-stopped \
            -p 3000:3000 \
            -e JWT_SECRET="$JWT_SECRET" \
            -e DB_PASSWORD="$DB_PASSWORD" \
            -e DB_USER="$DB_USER" \
            -e DB_HOST="$DB_HOST" \
            -e DB_PORT="$DB_PORT" \
            -e DB_NAME="$DB_NAME" \
            ticket-poc